# Generated by Django 5.1 on 2024-08-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_item',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='room_item_purchase',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
