# Generated by Django 5.1 on 2024-08-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_room_item_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='favorite',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
