# Generated by Django 5.1 on 2024-08-21 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.department')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.employee')),
                ('room_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.room_item')),
            ],
        ),
    ]
