# Generated by Django 5.1 on 2024-08-21 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_book_authors_alter_purchase_id_delete_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplepurchase',
            name='id',
        ),
        migrations.AddField(
            model_name='simplepurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
