# Generated by Django 5.1 on 2024-08-21 21:31

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_simplepurchase_id_simplepurchase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplepurchase',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), primary_key=True, serialize=False),
        ),
    ]
